### ISSUE TITLE
Oracle: add AaveOracle contract pointing on Stork oracle

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-core#43]

**Comment by msaug** [comment]
![image](https://user-images.githubusercontent.com/60658558/180847003-b97333e5-a0ee-44ba-917c-d33ea46e47d4.png)

**What should be implemented exactly?**

- An implementation of an Aave Oracle contract that relies on **[Stork Oracle](https://www.stork.network/)**
    - Instead of registering sources for each asset, we register a **ticker** (e.g. ETH/USD to get the ETHUSD price feed)
    - When calling set_asset_ticker, we bind one **asset address** to one **ticker**
- **A** **fallback oracle** should be implemented when possible. For now, **the calls to FallbackOracle are replaced with a return 0**

**What new libraries/dependencies needed (if any)?**

Depends on **ACLManager**. This contract has already been implemented in https://github.com/aave-starknet-project/aave-starknet-core/pull/42 and needs to be merged to main for the guard functions to work as expected.

**What are the possible test scenarios?**

NOTE: Since this contract relies on a 3rd-party (Stork), the tests only use mock data and we can't test with real-life price feeds for now.

- Test that the guard functions work as expected
- Test the registration of a ticker
- Test obtaining asset prices
