### ISSUE TITLE
Benchmark Stork and Empiric Network oracles

### ISSUE THREAD

**Issue by achab** [aave-starknet-project/aave-starknet-core#88]
Currently, two oracles are live on Starknet (testnet): [Stork](https://www.stork.network/) one and [Empiric Network](https://empiric.network/) one. The goal of this issue is to propose comparison methods (define a target price feed as baseline) and compare the precision, reliability, update frequency and additional features. Ideally comparison script is written in Python to enable further data analysis with pandas library. Final output is a Notion page explaining the process and the results.

Here are some useful references:

### Stork
- documentation: https://docs.stork.network/
- deployed contract: https://goerli.voyager.online/contract/0x0178a8866ef77a01df365b49d03fe46b8a90703e9fa1e10518277d12153b93d7
- contact: @msaug who worked on Stork's integration with our code base.

### Empiric Network
- documentation: https://docs.empiric.network/
- reference contract that consumes a price feed: https://github.com/42labs/Empiric/blob/master/contracts/sample_consumer/CheckEthThreshold.cairo
- python script to crawl events already emitted: https://github.com/42labs/Empiric/blob/master/analytics/crawl_events.py

**Comment by jonasalexander** [comment]
This is very exciting! I am Jonas, one of the co-founders of Empiric and am happy to be helpful where I can. Empiric has built a public, auditable track record of the network's performance by emitting an event for every price update which makes it easy to analyze our reliability and precision. We now have emitted 3.5M+ events over the last 4+ months and have built tooling to run benchmarking analyses. I see that Massil already posted the script to fetch events from the [Empiric oracle proxy](https://goerli.voyager.online/contract/0x012fadd18ec1a23a160cc46981400160fbf4a7a5eed156c4669e39807265bcd4#readContract) using StarkNet indexer, in addition we have benchmarking Python scripts & analysis Jupyter notebooks we can share. Feel free to take a look at our [codebase](https://github.com/42labs/Empiric/) (all open source since day 1) and reach out to me directly on Telegram @JonasNelle. Excited for the next phase of Aave on StarkNet!

**Comment by achab** [comment]
@MakC-Ukr I'm closing this issue since the blog post has been published.
